# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mb' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mb
  pod 'MobileCenter', '~> 0.10.1'
  pod 'RNMobileCenterShared', '~> 0.7.0'

  

  target 'mbTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mb-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mb-tvOS

  target 'mb-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
